server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ @front_rewrites;
    }

    location @front_rewrites {
        rewrite ^/search$ /search.php?$query_string last;
        rewrite ^/carte-du-monde$ /world.php?$query_string last;
        rewrite ^/category/([a-z0-9]+(?:-[a-z0-9]+)*)$ /category.php?slug=$1 last;
        rewrite ^/article/([a-z0-9]+(?:-[a-z0-9]+)*)-([0-9]+)\.html$ /article.php?slug=$1&id=$2 last;
        rewrite ^/$ /index.php?$query_string last;
        return 404;
    }

    location ^~ /assets/ {
        access_log off;
        expires 365d;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_index index.php;
        fastcgi_pass frontoffice-php:9000;
    }

    location ~ /\.ht {
        deny all;
    }
}
